### ISSUE TITLE
Wrong release date from SoundCloud

### ISSUE THREAD

**Issue by jesus2099** [garylaski/userscripts#13]
The only dates I can see on https://soundcloud.com/xjapanmusic/angel is 2023-07-28 (post date and published date).
But the importer said 2023-07-20: https://musicbrainz.org/edit/102703093

**Comment by garylaski** [comment]
The soundcloud hydration data has several fields for date. In your example:
```json
"created_at": "2023-07-20T15:17:55Z"
"display_date": "2023-07-28T00:00:00Z"
"release_date": "2023-07-28T00:00:00Z"
```
In this case, what you want is `release_date` or `display_date`, which is a date value set by the artist. The `created_at` value is what this script is using, which is when the track was uploaded. 

In some cases, the `release_date` field is null, incorrect or purposefully abused, which is why I originally chose the `created_at` field for getting date information from (this was a bad choice). 

I'll update the script to use the `display_date` field, which seems to have more logical dates.

**Comment by jesus2099** [comment]
Thank you for your explanation!
